// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: alk_main_pvt.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// ActiveLook Private/Debug Protobuf communication
// This channel is for test and debug commands not available in the public API
//
// Transport: binary protocol command ID 0xBC
// All private protobuf commands (PvtCommandWrapper) are sent with cmd_id=0xBC.
// Responses (PvtResponseWrapper) are returned on the same command ID.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Generic message to request data
public struct AlkpbPvt_EmptyRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// dummy parameter to ensure non-empty serialization for betterproto/nanopb compatibility
  /// must not be set to 0 to ensure the field is included in the serialized message
  public var dummy: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// LVGL heap info - memory statistics
public struct AlkpbPvt_LvglHeapInfoResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var freeBytes: Int32 = 0

  public var allocatedBytes: Int32 = 0

  public var maxAllocatedBytes: Int32 = 0

  public var totalBytes: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Main wrapper for private/debug commands sent to the device
public struct AlkpbPvt_PvtCommandWrapper: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var msg: AlkpbPvt_PvtCommandWrapper.OneOf_Msg? = nil

  public var lvglHeapInfo: AlkpbPvt_EmptyRequest {
    get {
      if case .lvglHeapInfo(let v)? = msg {return v}
      return AlkpbPvt_EmptyRequest()
    }
    set {msg = .lvglHeapInfo(newValue)}
  }

  /// Companion App Filesystem commands
  public var fsList: AlkpbPvt_FsListRequest {
    get {
      if case .fsList(let v)? = msg {return v}
      return AlkpbPvt_FsListRequest()
    }
    set {msg = .fsList(newValue)}
  }

  public var fsMkdir: AlkpbPvt_FsMkdirRequest {
    get {
      if case .fsMkdir(let v)? = msg {return v}
      return AlkpbPvt_FsMkdirRequest()
    }
    set {msg = .fsMkdir(newValue)}
  }

  public var fsRead: AlkpbPvt_FsReadRequest {
    get {
      if case .fsRead(let v)? = msg {return v}
      return AlkpbPvt_FsReadRequest()
    }
    set {msg = .fsRead(newValue)}
  }

  public var fsWrite: AlkpbPvt_FsWriteRequest {
    get {
      if case .fsWrite(let v)? = msg {return v}
      return AlkpbPvt_FsWriteRequest()
    }
    set {msg = .fsWrite(newValue)}
  }

  public var fsDelete: AlkpbPvt_FsDeleteRequest {
    get {
      if case .fsDelete(let v)? = msg {return v}
      return AlkpbPvt_FsDeleteRequest()
    }
    set {msg = .fsDelete(newValue)}
  }

  public var fsRmdir: AlkpbPvt_FsRmdirRequest {
    get {
      if case .fsRmdir(let v)? = msg {return v}
      return AlkpbPvt_FsRmdirRequest()
    }
    set {msg = .fsRmdir(newValue)}
  }

  public var fsRename: AlkpbPvt_FsRenameRequest {
    get {
      if case .fsRename(let v)? = msg {return v}
      return AlkpbPvt_FsRenameRequest()
    }
    set {msg = .fsRename(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Msg: Equatable, Sendable {
    case lvglHeapInfo(AlkpbPvt_EmptyRequest)
    /// Companion App Filesystem commands
    case fsList(AlkpbPvt_FsListRequest)
    case fsMkdir(AlkpbPvt_FsMkdirRequest)
    case fsRead(AlkpbPvt_FsReadRequest)
    case fsWrite(AlkpbPvt_FsWriteRequest)
    case fsDelete(AlkpbPvt_FsDeleteRequest)
    case fsRmdir(AlkpbPvt_FsRmdirRequest)
    case fsRename(AlkpbPvt_FsRenameRequest)

  }

  public init() {}
}

/// Response wrapper for private/debug command responses from the device
public struct AlkpbPvt_PvtResponseWrapper: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var msg: AlkpbPvt_PvtResponseWrapper.OneOf_Msg? = nil

  public var lvglHeapInfo: AlkpbPvt_LvglHeapInfoResponse {
    get {
      if case .lvglHeapInfo(let v)? = msg {return v}
      return AlkpbPvt_LvglHeapInfoResponse()
    }
    set {msg = .lvglHeapInfo(newValue)}
  }

  /// Companion App Filesystem responses
  public var fsList: AlkpbPvt_FsListResponse {
    get {
      if case .fsList(let v)? = msg {return v}
      return AlkpbPvt_FsListResponse()
    }
    set {msg = .fsList(newValue)}
  }

  public var fsRead: AlkpbPvt_FsReadResponse {
    get {
      if case .fsRead(let v)? = msg {return v}
      return AlkpbPvt_FsReadResponse()
    }
    set {msg = .fsRead(newValue)}
  }

  /// Shared response for mkdir, write, delete, rmdir
  public var fsResult: AlkpbPvt_FsResultResponse {
    get {
      if case .fsResult(let v)? = msg {return v}
      return AlkpbPvt_FsResultResponse()
    }
    set {msg = .fsResult(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Msg: Equatable, Sendable {
    case lvglHeapInfo(AlkpbPvt_LvglHeapInfoResponse)
    /// Companion App Filesystem responses
    case fsList(AlkpbPvt_FsListResponse)
    case fsRead(AlkpbPvt_FsReadResponse)
    /// Shared response for mkdir, write, delete, rmdir
    case fsResult(AlkpbPvt_FsResultResponse)

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "alkpb_pvt"

extension AlkpbPvt_EmptyRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".EmptyRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}dummy\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.dummy) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.dummy != 0 {
      try visitor.visitSingularInt32Field(value: self.dummy, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AlkpbPvt_EmptyRequest, rhs: AlkpbPvt_EmptyRequest) -> Bool {
    if lhs.dummy != rhs.dummy {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AlkpbPvt_LvglHeapInfoResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LvglHeapInfoResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}free_bytes\0\u{3}allocated_bytes\0\u{3}max_allocated_bytes\0\u{3}total_bytes\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.freeBytes) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.allocatedBytes) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.maxAllocatedBytes) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.totalBytes) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.freeBytes != 0 {
      try visitor.visitSingularInt32Field(value: self.freeBytes, fieldNumber: 1)
    }
    if self.allocatedBytes != 0 {
      try visitor.visitSingularInt32Field(value: self.allocatedBytes, fieldNumber: 2)
    }
    if self.maxAllocatedBytes != 0 {
      try visitor.visitSingularInt32Field(value: self.maxAllocatedBytes, fieldNumber: 3)
    }
    if self.totalBytes != 0 {
      try visitor.visitSingularInt32Field(value: self.totalBytes, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AlkpbPvt_LvglHeapInfoResponse, rhs: AlkpbPvt_LvglHeapInfoResponse) -> Bool {
    if lhs.freeBytes != rhs.freeBytes {return false}
    if lhs.allocatedBytes != rhs.allocatedBytes {return false}
    if lhs.maxAllocatedBytes != rhs.maxAllocatedBytes {return false}
    if lhs.totalBytes != rhs.totalBytes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AlkpbPvt_PvtCommandWrapper: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PvtCommandWrapper"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}lvgl_heap_info\0\u{4}\u{9}fs_list\0\u{3}fs_mkdir\0\u{3}fs_read\0\u{3}fs_write\0\u{3}fs_delete\0\u{3}fs_rmdir\0\u{3}fs_rename\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: AlkpbPvt_EmptyRequest?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .lvglHeapInfo(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .lvglHeapInfo(v)
        }
      }()
      case 10: try {
        var v: AlkpbPvt_FsListRequest?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .fsList(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .fsList(v)
        }
      }()
      case 11: try {
        var v: AlkpbPvt_FsMkdirRequest?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .fsMkdir(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .fsMkdir(v)
        }
      }()
      case 12: try {
        var v: AlkpbPvt_FsReadRequest?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .fsRead(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .fsRead(v)
        }
      }()
      case 13: try {
        var v: AlkpbPvt_FsWriteRequest?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .fsWrite(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .fsWrite(v)
        }
      }()
      case 14: try {
        var v: AlkpbPvt_FsDeleteRequest?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .fsDelete(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .fsDelete(v)
        }
      }()
      case 15: try {
        var v: AlkpbPvt_FsRmdirRequest?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .fsRmdir(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .fsRmdir(v)
        }
      }()
      case 16: try {
        var v: AlkpbPvt_FsRenameRequest?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .fsRename(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .fsRename(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.msg {
    case .lvglHeapInfo?: try {
      guard case .lvglHeapInfo(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .fsList?: try {
      guard case .fsList(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .fsMkdir?: try {
      guard case .fsMkdir(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .fsRead?: try {
      guard case .fsRead(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case .fsWrite?: try {
      guard case .fsWrite(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
    }()
    case .fsDelete?: try {
      guard case .fsDelete(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
    }()
    case .fsRmdir?: try {
      guard case .fsRmdir(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
    }()
    case .fsRename?: try {
      guard case .fsRename(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 16)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AlkpbPvt_PvtCommandWrapper, rhs: AlkpbPvt_PvtCommandWrapper) -> Bool {
    if lhs.msg != rhs.msg {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AlkpbPvt_PvtResponseWrapper: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PvtResponseWrapper"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}lvgl_heap_info\0\u{4}\u{9}fs_list\0\u{3}fs_read\0\u{3}fs_result\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: AlkpbPvt_LvglHeapInfoResponse?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .lvglHeapInfo(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .lvglHeapInfo(v)
        }
      }()
      case 10: try {
        var v: AlkpbPvt_FsListResponse?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .fsList(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .fsList(v)
        }
      }()
      case 11: try {
        var v: AlkpbPvt_FsReadResponse?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .fsRead(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .fsRead(v)
        }
      }()
      case 12: try {
        var v: AlkpbPvt_FsResultResponse?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .fsResult(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .fsResult(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.msg {
    case .lvglHeapInfo?: try {
      guard case .lvglHeapInfo(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .fsList?: try {
      guard case .fsList(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .fsRead?: try {
      guard case .fsRead(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .fsResult?: try {
      guard case .fsResult(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AlkpbPvt_PvtResponseWrapper, rhs: AlkpbPvt_PvtResponseWrapper) -> Bool {
    if lhs.msg != rhs.msg {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
