// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: alk_save_asset.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// ActiveLook Graphical asset saving

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Format below are MDP05 compatible
public enum Alkpb_PixelFormatMdp05: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Yellow monochrome, 4 bit per pixel (bpp)
  case mono4Bpp // = 0

  /// Yellow monochrome, 1 bpp
  case mono1Bpp // = 1

  /// Yellow monochrome, 4 bpp, data compressed
  case mono4BppHeatshrink // = 2

  /// Yellow monochrome, 4 bpp for color + 4 bpp for transparency
  case mono8BppAlpha // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .mono4Bpp
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .mono4Bpp
    case 1: self = .mono1Bpp
    case 2: self = .mono4BppHeatshrink
    case 3: self = .mono8BppAlpha
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .mono4Bpp: return 0
    case .mono1Bpp: return 1
    case .mono4BppHeatshrink: return 2
    case .mono8BppAlpha: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Alkpb_PixelFormatMdp05] = [
    .mono4Bpp,
    .mono1Bpp,
    .mono4BppHeatshrink,
    .mono8BppAlpha,
  ]

}

/// Format below are MDP058 compatible
public enum Alkpb_PixelFormatMdp08: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Red/Green, 8 bit per pixel (bpp), data compressed
  case rrgg8Bpp // = 0

  /// Red/Green, 8 bpp for color + 4 bpp for transparency [color_pxl1, color_pxl2, alpha pxl1 & alpha pxl2], data compressed
  case rrgg12BppAlpha // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .rrgg8Bpp
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .rrgg8Bpp
    case 1: self = .rrgg12BppAlpha
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .rrgg8Bpp: return 0
    case .rrgg12BppAlpha: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Alkpb_PixelFormatMdp08] = [
    .rrgg8Bpp,
    .rrgg12BppAlpha,
  ]

}

public struct Alkpb_PixelFormat: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var pixelFormat: Alkpb_PixelFormat.OneOf_PixelFormat? = nil

  public var pixelFormatMdp05: Alkpb_PixelFormatMdp05 {
    get {
      if case .pixelFormatMdp05(let v)? = pixelFormat {return v}
      return .mono4Bpp
    }
    set {pixelFormat = .pixelFormatMdp05(newValue)}
  }

  public var pixelFormatMdp08: Alkpb_PixelFormatMdp08 {
    get {
      if case .pixelFormatMdp08(let v)? = pixelFormat {return v}
      return .rrgg8Bpp
    }
    set {pixelFormat = .pixelFormatMdp08(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_PixelFormat: Equatable, Sendable {
    case pixelFormatMdp05(Alkpb_PixelFormatMdp05)
    case pixelFormatMdp08(Alkpb_PixelFormatMdp08)

  }

  public init() {}
}

/// Image metadata
public struct Alkpb_ImageMetadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Format of the image data
  public var format: Alkpb_PixelFormat {
    get {return _format ?? Alkpb_PixelFormat()}
    set {_format = newValue}
  }
  /// Returns true if `format` has been explicitly set.
  public var hasFormat: Bool {return self._format != nil}
  /// Clears the value of `format`. Subsequent reads from it will return its default value.
  public mutating func clearFormat() {self._format = nil}

  /// Raw data size in bytes (before heatshrink compression if applicable)
  public var dataSize: Int32 = 0

  /// Width in pixels
  public var width: Int32 = 0

  /// Height in pixels
  public var height: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _format: Alkpb_PixelFormat? = nil
}

/// Animation metadata
public struct Alkpb_AnimationMetadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Reference frame (1st image) metadata
  public var refFrameMetadata: Alkpb_ImageMetadata {
    get {return _refFrameMetadata ?? Alkpb_ImageMetadata()}
    set {_refFrameMetadata = newValue}
  }
  /// Returns true if `refFrameMetadata` has been explicitly set.
  public var hasRefFrameMetadata: Bool {return self._refFrameMetadata != nil}
  /// Clears the value of `refFrameMetadata`. Subsequent reads from it will return its default value.
  public mutating func clearRefFrameMetadata() {self._refFrameMetadata = nil}

  /// Compressed reference frame (1st image) size in bytes (for uncompressed format is equal to ref_img_size)
  public var refImgCompressedSize: Int32 = 0

  /// Full animation raw data size in bytes (after heatshrink compression if applicable)
  public var totalCompressedSize: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _refFrameMetadata: Alkpb_ImageMetadata? = nil
}

public struct Alkpb_AssetMetadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var assetID: Int32 = 0

  public var assetMetadata: Alkpb_AssetMetadata.OneOf_AssetMetadata? = nil

  public var image: Alkpb_ImageMetadata {
    get {
      if case .image(let v)? = assetMetadata {return v}
      return Alkpb_ImageMetadata()
    }
    set {assetMetadata = .image(newValue)}
  }

  public var animation: Alkpb_AnimationMetadata {
    get {
      if case .animation(let v)? = assetMetadata {return v}
      return Alkpb_AnimationMetadata()
    }
    set {assetMetadata = .animation(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_AssetMetadata: Equatable, Sendable {
    case image(Alkpb_ImageMetadata)
    case animation(Alkpb_AnimationMetadata)

  }

  public init() {}
}

/// Data chunk for progressive asset uploading
public struct Alkpb_AssetDataChunk: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Chunk index starts at 0 and increases sequentially
  public var chunkIndex: Int32 = 0

  /// Binary data for this chunk
  public var chunkData: Data = Data()

  /// True if this is the final chunk of the asset
  public var isLastChunk: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Save a graphical asset (image, animation, etc)
/// Usage flow:
/// 1. Send metadata message first with asset details
/// 2. Send data chunks sequentially until complete
public struct Alkpb_SaveAssetRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var data: Alkpb_SaveAssetRequest.OneOf_Data? = nil

  public var metadata: Alkpb_AssetMetadata {
    get {
      if case .metadata(let v)? = data {return v}
      return Alkpb_AssetMetadata()
    }
    set {data = .metadata(newValue)}
  }

  public var dataChunk: Alkpb_AssetDataChunk {
    get {
      if case .dataChunk(let v)? = data {return v}
      return Alkpb_AssetDataChunk()
    }
    set {data = .dataChunk(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Data: Equatable, Sendable {
    case metadata(Alkpb_AssetMetadata)
    case dataChunk(Alkpb_AssetDataChunk)

  }

  public init() {}
}

/// Delete a graphical asset (image, animation, etc)
public struct Alkpb_DeleteAssetRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var assetID: Alkpb_DeleteAssetRequest.OneOf_AssetID? = nil

  public var imageID: Int32 {
    get {
      if case .imageID(let v)? = assetID {return v}
      return 0
    }
    set {assetID = .imageID(newValue)}
  }

  public var animID: Int32 {
    get {
      if case .animID(let v)? = assetID {return v}
      return 0
    }
    set {assetID = .animID(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_AssetID: Equatable, Sendable {
    case imageID(Int32)
    case animID(Int32)

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "alkpb"

extension Alkpb_PixelFormatMdp05: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0MONO_4BPP\0\u{1}MONO_1BPP\0\u{1}MONO_4BPP_HEATSHRINK\0\u{1}MONO_8BPP_ALPHA\0")
}

extension Alkpb_PixelFormatMdp08: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RRGG_8BPP\0\u{1}RRGG_12BPP_ALPHA\0")
}

extension Alkpb_PixelFormat: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PixelFormat"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}pixel_format_mdp05\0\u{3}pixel_format_mdp08\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Alkpb_PixelFormatMdp05?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.pixelFormat != nil {try decoder.handleConflictingOneOf()}
          self.pixelFormat = .pixelFormatMdp05(v)
        }
      }()
      case 2: try {
        var v: Alkpb_PixelFormatMdp08?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.pixelFormat != nil {try decoder.handleConflictingOneOf()}
          self.pixelFormat = .pixelFormatMdp08(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.pixelFormat {
    case .pixelFormatMdp05?: try {
      guard case .pixelFormatMdp05(let v)? = self.pixelFormat else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    }()
    case .pixelFormatMdp08?: try {
      guard case .pixelFormatMdp08(let v)? = self.pixelFormat else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_PixelFormat, rhs: Alkpb_PixelFormat) -> Bool {
    if lhs.pixelFormat != rhs.pixelFormat {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_ImageMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ImageMetadata"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}format\0\u{3}data_size\0\u{1}width\0\u{1}height\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._format) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.dataSize) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.width) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.height) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._format {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.dataSize != 0 {
      try visitor.visitSingularInt32Field(value: self.dataSize, fieldNumber: 2)
    }
    if self.width != 0 {
      try visitor.visitSingularInt32Field(value: self.width, fieldNumber: 3)
    }
    if self.height != 0 {
      try visitor.visitSingularInt32Field(value: self.height, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_ImageMetadata, rhs: Alkpb_ImageMetadata) -> Bool {
    if lhs._format != rhs._format {return false}
    if lhs.dataSize != rhs.dataSize {return false}
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_AnimationMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AnimationMetadata"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}ref_frame_metadata\0\u{3}ref_img_compressed_size\0\u{3}total_compressed_size\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._refFrameMetadata) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.refImgCompressedSize) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.totalCompressedSize) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._refFrameMetadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.refImgCompressedSize != 0 {
      try visitor.visitSingularInt32Field(value: self.refImgCompressedSize, fieldNumber: 2)
    }
    if self.totalCompressedSize != 0 {
      try visitor.visitSingularInt32Field(value: self.totalCompressedSize, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_AnimationMetadata, rhs: Alkpb_AnimationMetadata) -> Bool {
    if lhs._refFrameMetadata != rhs._refFrameMetadata {return false}
    if lhs.refImgCompressedSize != rhs.refImgCompressedSize {return false}
    if lhs.totalCompressedSize != rhs.totalCompressedSize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_AssetMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AssetMetadata"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}asset_id\0\u{1}image\0\u{1}animation\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.assetID) }()
      case 2: try {
        var v: Alkpb_ImageMetadata?
        var hadOneofValue = false
        if let current = self.assetMetadata {
          hadOneofValue = true
          if case .image(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.assetMetadata = .image(v)
        }
      }()
      case 3: try {
        var v: Alkpb_AnimationMetadata?
        var hadOneofValue = false
        if let current = self.assetMetadata {
          hadOneofValue = true
          if case .animation(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.assetMetadata = .animation(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.assetID != 0 {
      try visitor.visitSingularInt32Field(value: self.assetID, fieldNumber: 1)
    }
    switch self.assetMetadata {
    case .image?: try {
      guard case .image(let v)? = self.assetMetadata else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .animation?: try {
      guard case .animation(let v)? = self.assetMetadata else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_AssetMetadata, rhs: Alkpb_AssetMetadata) -> Bool {
    if lhs.assetID != rhs.assetID {return false}
    if lhs.assetMetadata != rhs.assetMetadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_AssetDataChunk: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AssetDataChunk"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}chunk_index\0\u{3}chunk_data\0\u{3}is_last_chunk\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.chunkIndex) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.chunkData) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isLastChunk) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.chunkIndex != 0 {
      try visitor.visitSingularInt32Field(value: self.chunkIndex, fieldNumber: 1)
    }
    if !self.chunkData.isEmpty {
      try visitor.visitSingularBytesField(value: self.chunkData, fieldNumber: 2)
    }
    if self.isLastChunk != false {
      try visitor.visitSingularBoolField(value: self.isLastChunk, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_AssetDataChunk, rhs: Alkpb_AssetDataChunk) -> Bool {
    if lhs.chunkIndex != rhs.chunkIndex {return false}
    if lhs.chunkData != rhs.chunkData {return false}
    if lhs.isLastChunk != rhs.isLastChunk {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_SaveAssetRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SaveAssetRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}metadata\0\u{3}data_chunk\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Alkpb_AssetMetadata?
        var hadOneofValue = false
        if let current = self.data {
          hadOneofValue = true
          if case .metadata(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.data = .metadata(v)
        }
      }()
      case 2: try {
        var v: Alkpb_AssetDataChunk?
        var hadOneofValue = false
        if let current = self.data {
          hadOneofValue = true
          if case .dataChunk(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.data = .dataChunk(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.data {
    case .metadata?: try {
      guard case .metadata(let v)? = self.data else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .dataChunk?: try {
      guard case .dataChunk(let v)? = self.data else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_SaveAssetRequest, rhs: Alkpb_SaveAssetRequest) -> Bool {
    if lhs.data != rhs.data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_DeleteAssetRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeleteAssetRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}image_id\0\u{3}anim_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Int32?
        try decoder.decodeSingularInt32Field(value: &v)
        if let v = v {
          if self.assetID != nil {try decoder.handleConflictingOneOf()}
          self.assetID = .imageID(v)
        }
      }()
      case 2: try {
        var v: Int32?
        try decoder.decodeSingularInt32Field(value: &v)
        if let v = v {
          if self.assetID != nil {try decoder.handleConflictingOneOf()}
          self.assetID = .animID(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.assetID {
    case .imageID?: try {
      guard case .imageID(let v)? = self.assetID else { preconditionFailure() }
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    }()
    case .animID?: try {
      guard case .animID(let v)? = self.assetID else { preconditionFailure() }
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_DeleteAssetRequest, rhs: Alkpb_DeleteAssetRequest) -> Bool {
    if lhs.assetID != rhs.assetID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
