// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: alk_main.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// ActiveLook Protobuf communication

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Alkpb_CompletionMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// The Done part is Highlighted
  case done // = 0

  /// The Remaining part is Highlighted
  case remain // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .done
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .done
    case 1: self = .remain
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .done: return 0
    case .remain: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Alkpb_CompletionMode] = [
    .done,
    .remain,
  ]

}

///*
/// Enum for widget style
/// The widget style embed several hard-coded value: Text font, Bar style of shape, etc...
public enum Alkpb_WidgetStyle: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Take 1 LayoutPosition slot 
  case half // = 0

  /// Take 2 LayoutPosition slots, 1 row
  case thin // = 1

  /// Take 4 LayoutPosition slots, 2 rows, 2 columns 
  case large // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .half
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .half
    case 1: self = .thin
    case 2: self = .large
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .half: return 0
    case .thin: return 1
    case .large: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Alkpb_WidgetStyle] = [
    .half,
    .thin,
    .large,
  ]

}

///*
/// Layout position
/// Slots disposition:
/// -------------
/// |  0  |  1  |
/// -------------
/// |  2  |  3  |
/// -------------
/// |  4  |  5  |
/// -------------
public enum Alkpb_LayoutPosition: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case topLeft // = 0
  case topRight // = 1
  case midLeft // = 2
  case midRight // = 3
  case botLeft // = 4
  case botRight // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .topLeft
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .topLeft
    case 1: self = .topRight
    case 2: self = .midLeft
    case 3: self = .midRight
    case 4: self = .botLeft
    case 5: self = .botRight
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .topLeft: return 0
    case .topRight: return 1
    case .midLeft: return 2
    case .midRight: return 3
    case .botLeft: return 4
    case .botRight: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Alkpb_LayoutPosition] = [
    .topLeft,
    .topRight,
    .midLeft,
    .midRight,
    .botLeft,
    .botRight,
  ]

}

public enum Alkpb_TransitionType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case none // = 0

  /// left slide
  case slide // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .none
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .none
    case 1: self = .slide
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .none: return 0
    case .slide: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Alkpb_TransitionType] = [
    .none,
    .slide,
  ]

}

/// Common base fields for most WidgetType
public struct Alkpb_BaseData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Cannot be 0
  public var iconID: Int32 = 0

  public var label: String = String()

  public var unit: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Common bar-related structure
public struct Alkpb_BarData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var baseData: Alkpb_BaseData {
    get {return _baseData ?? Alkpb_BaseData()}
    set {_baseData = newValue}
  }
  /// Returns true if `baseData` has been explicitly set.
  public var hasBaseData: Bool {return self._baseData != nil}
  /// Clears the value of `baseData`. Subsequent reads from it will return its default value.
  public mutating func clearBaseData() {self._baseData = nil}

  /// ARRAY SIZE: 7, if empty, default firmware values are used,
  public var zonesColors: [Int32] = []

  public var displayIndicator: Bool = false

  ///*
  /// disabled_zones_ratio
  /// Width percentage of disabled zone
  /// Constraint: sum of the array items should be below 90
  /// Constraint: percentage of one item cannot be below 10
  /// Enabled zone width = 100 + disabled_zones_ratio[chosen zone index] − sum(disabled_zones_ratio)
  /// If empty, default firmware values are used
  public var disabledZonesRatio: [Int32] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _baseData: Alkpb_BaseData? = nil
}

public struct Alkpb_CompletionData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var baseData: Alkpb_BaseData {
    get {return _baseData ?? Alkpb_BaseData()}
    set {_baseData = newValue}
  }
  /// Returns true if `baseData` has been explicitly set.
  public var hasBaseData: Bool {return self._baseData != nil}
  /// Clears the value of `baseData`. Subsequent reads from it will return its default value.
  public mutating func clearBaseData() {self._baseData = nil}

  public var doneColor: Int32 = 0

  public var toDoColor: Int32 = 0

  public var completionMode: Alkpb_CompletionMode = .done

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _baseData: Alkpb_BaseData? = nil
}

public struct Alkpb_TextData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Cannot be 0
  public var iconID: Int32 = 0

  public var textText: String = String()

  public var textColor: Int32 = 0

  /// 0 is the default font for text
  public var textFontID: Int32 = 0

  public var titleText: String = String()

  public var titleColor: Int32 = 0

  ///  0 is the default font for title
  public var titleFontID: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Alkpb_PlainTextData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var textText: String = String()

  public var textColor: Int32 = 0

  /// 0 is the default font for text
  public var textFontID: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Alkpb_ImageData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Cannot be 0
  public var imageID: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Alkpb_AnimData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Cannot be 0
  public var animID: Int32 = 0

  /// If -1, infinite  repeat
  public var repeatCount: Int32 = 0

  public var frameTimeMs: Int32 = 0

  /// If it is true, widget area is cleaned at the end of the repetitions or if StopAnim message is sent
  public var cleanAtEnd: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Alkpb_WidgetConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var type: Alkpb_WidgetConfig.OneOf_Type? = nil

  public var metric: Alkpb_BaseData {
    get {
      if case .metric(let v)? = type {return v}
      return Alkpb_BaseData()
    }
    set {type = .metric(newValue)}
  }

  public var zones7: Alkpb_BarData {
    get {
      if case .zones7(let v)? = type {return v}
      return Alkpb_BarData()
    }
    set {type = .zones7(newValue)}
  }

  public var zones5: Alkpb_BarData {
    get {
      if case .zones5(let v)? = type {return v}
      return Alkpb_BarData()
    }
    set {type = .zones5(newValue)}
  }

  public var range: Alkpb_BarData {
    get {
      if case .range(let v)? = type {return v}
      return Alkpb_BarData()
    }
    set {type = .range(newValue)}
  }

  public var threshold: Alkpb_BarData {
    get {
      if case .threshold(let v)? = type {return v}
      return Alkpb_BarData()
    }
    set {type = .threshold(newValue)}
  }

  public var completion: Alkpb_CompletionData {
    get {
      if case .completion(let v)? = type {return v}
      return Alkpb_CompletionData()
    }
    set {type = .completion(newValue)}
  }

  public var text: Alkpb_TextData {
    get {
      if case .text(let v)? = type {return v}
      return Alkpb_TextData()
    }
    set {type = .text(newValue)}
  }

  public var shortText: Alkpb_TextData {
    get {
      if case .shortText(let v)? = type {return v}
      return Alkpb_TextData()
    }
    set {type = .shortText(newValue)}
  }

  public var plainText: Alkpb_PlainTextData {
    get {
      if case .plainText(let v)? = type {return v}
      return Alkpb_PlainTextData()
    }
    set {type = .plainText(newValue)}
  }

  public var image: Alkpb_ImageData {
    get {
      if case .image(let v)? = type {return v}
      return Alkpb_ImageData()
    }
    set {type = .image(newValue)}
  }

  public var anim: Alkpb_AnimData {
    get {
      if case .anim(let v)? = type {return v}
      return Alkpb_AnimData()
    }
    set {type = .anim(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Type: Equatable, Sendable {
    case metric(Alkpb_BaseData)
    case zones7(Alkpb_BarData)
    case zones5(Alkpb_BarData)
    case range(Alkpb_BarData)
    case threshold(Alkpb_BarData)
    case completion(Alkpb_CompletionData)
    case text(Alkpb_TextData)
    case shortText(Alkpb_TextData)
    case plainText(Alkpb_PlainTextData)
    case image(Alkpb_ImageData)
    case anim(Alkpb_AnimData)

  }

  public init() {}
}

public struct Alkpb_RawPosition: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Origin of screen (0,0) is at the top-left
  public var x: Int32 = 0

  /// Origin of screen (0,0) is at the top-left
  public var y: Int32 = 0

  /// Overwrite size of widget if filled or if height filled
  public var width: Int32 = 0

  /// Overwrite size of widget if filled or if width filled
  public var height: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Alkpb_Widget: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///* 
  /// data_id
  /// Represents data to update, you can have several widget with the same data_id.
  /// These widgets will be all updated when you make an UpdateWidgetsDataRequest call on this data_id
  public var dataID: Int32 = 0

  public var config: Alkpb_WidgetConfig {
    get {return _config ?? Alkpb_WidgetConfig()}
    set {_config = newValue}
  }
  /// Returns true if `config` has been explicitly set.
  public var hasConfig: Bool {return self._config != nil}
  /// Clears the value of `config`. Subsequent reads from it will return its default value.
  public mutating func clearConfig() {self._config = nil}

  public var style: Alkpb_WidgetStyle = .half

  public var position: Alkpb_Widget.OneOf_Position? = nil

  public var layoutPosition: Alkpb_LayoutPosition {
    get {
      if case .layoutPosition(let v)? = position {return v}
      return .topLeft
    }
    set {position = .layoutPosition(newValue)}
  }

  public var rawPosition: Alkpb_RawPosition {
    get {
      if case .rawPosition(let v)? = position {return v}
      return Alkpb_RawPosition()
    }
    set {position = .rawPosition(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Position: Equatable, Sendable {
    case layoutPosition(Alkpb_LayoutPosition)
    case rawPosition(Alkpb_RawPosition)

  }

  public init() {}

  fileprivate var _config: Alkpb_WidgetConfig? = nil
}

public struct Alkpb_SetScreenRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Cannot be 0
  public var screenID: Int32 = 0

  /// ARRAY SIZE: 6
  public var widgets: [Alkpb_Widget] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Alkpb_DisplayScreenRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Cannot be 0
  public var screenID: Int32 = 0

  public var transitionType: Alkpb_TransitionType = .none

  ///* duration_ms
  /// If duration_ms specified, the screen is considered as a popup-screen :
  /// A screen which appears over the current screen for a specified amount of time
  /// Transition type is used for in and out of the screen.
  public var durationMs: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Alkpb_Value: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var leftValue: String = String()

  public var middleValue: String = String()

  public var rightValue: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Update widget zone data
public struct Alkpb_WidgetZoneData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// chosen zone start at index 1. No zone update when index is set to 0
  public var chosenZone: Int32 = 0

  /// position of the value indicator on the chosen_zone in percentage
  public var indicatorPosition: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Update widget data
public struct Alkpb_WidgetData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Cannot be 0
  public var dataID: Int32 = 0

  public var value: Alkpb_Value {
    get {return _value ?? Alkpb_Value()}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  public var hasValue: Bool {return self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  public mutating func clearValue() {self._value = nil}

  public var widgetZoneData: Alkpb_WidgetZoneData {
    get {return _widgetZoneData ?? Alkpb_WidgetZoneData()}
    set {_widgetZoneData = newValue}
  }
  /// Returns true if `widgetZoneData` has been explicitly set.
  public var hasWidgetZoneData: Bool {return self._widgetZoneData != nil}
  /// Clears the value of `widgetZoneData`. Subsequent reads from it will return its default value.
  public mutating func clearWidgetZoneData() {self._widgetZoneData = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _value: Alkpb_Value? = nil
  fileprivate var _widgetZoneData: Alkpb_WidgetZoneData? = nil
}

public struct Alkpb_UpdateWidgetsDataRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// ARRAY SIZE: 6
  public var updateWidgets: [Alkpb_WidgetData] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Send a message to stop asynchronously a running animation.
public struct Alkpb_StopAnimRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Cannot be 0
  public var dataID: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Alkpb_CommandWrapper: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var msg: Alkpb_CommandWrapper.OneOf_Msg? = nil

  /// Max 20 screens allowed
  public var setScreen: Alkpb_SetScreenRequest {
    get {
      if case .setScreen(let v)? = msg {return v}
      return Alkpb_SetScreenRequest()
    }
    set {msg = .setScreen(newValue)}
  }

  public var displayScreen: Alkpb_DisplayScreenRequest {
    get {
      if case .displayScreen(let v)? = msg {return v}
      return Alkpb_DisplayScreenRequest()
    }
    set {msg = .displayScreen(newValue)}
  }

  public var updateWidgetsData: Alkpb_UpdateWidgetsDataRequest {
    get {
      if case .updateWidgetsData(let v)? = msg {return v}
      return Alkpb_UpdateWidgetsDataRequest()
    }
    set {msg = .updateWidgetsData(newValue)}
  }

  public var stopAnim: Alkpb_StopAnimRequest {
    get {
      if case .stopAnim(let v)? = msg {return v}
      return Alkpb_StopAnimRequest()
    }
    set {msg = .stopAnim(newValue)}
  }

  public var saveAsset: Alkpb_SaveAssetRequest {
    get {
      if case .saveAsset(let v)? = msg {return v}
      return Alkpb_SaveAssetRequest()
    }
    set {msg = .saveAsset(newValue)}
  }

  public var deleteAsset: Alkpb_DeleteAssetRequest {
    get {
      if case .deleteAsset(let v)? = msg {return v}
      return Alkpb_DeleteAssetRequest()
    }
    set {msg = .deleteAsset(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Msg: Equatable, Sendable {
    /// Max 20 screens allowed
    case setScreen(Alkpb_SetScreenRequest)
    case displayScreen(Alkpb_DisplayScreenRequest)
    case updateWidgetsData(Alkpb_UpdateWidgetsDataRequest)
    case stopAnim(Alkpb_StopAnimRequest)
    case saveAsset(Alkpb_SaveAssetRequest)
    case deleteAsset(Alkpb_DeleteAssetRequest)

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "alkpb"

extension Alkpb_CompletionMode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DONE\0\u{1}REMAIN\0")
}

extension Alkpb_WidgetStyle: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0HALF\0\u{1}THIN\0\u{1}LARGE\0")
}

extension Alkpb_LayoutPosition: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0TOP_LEFT\0\u{1}TOP_RIGHT\0\u{1}MID_LEFT\0\u{1}MID_RIGHT\0\u{1}BOT_LEFT\0\u{1}BOT_RIGHT\0")
}

extension Alkpb_TransitionType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0NONE\0\u{1}SLIDE\0")
}

extension Alkpb_BaseData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BaseData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}icon_id\0\u{1}label\0\u{1}unit\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.iconID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.label) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.unit) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.iconID != 0 {
      try visitor.visitSingularInt32Field(value: self.iconID, fieldNumber: 1)
    }
    if !self.label.isEmpty {
      try visitor.visitSingularStringField(value: self.label, fieldNumber: 2)
    }
    if !self.unit.isEmpty {
      try visitor.visitSingularStringField(value: self.unit, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_BaseData, rhs: Alkpb_BaseData) -> Bool {
    if lhs.iconID != rhs.iconID {return false}
    if lhs.label != rhs.label {return false}
    if lhs.unit != rhs.unit {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_BarData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BarData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}base_data\0\u{3}zones_colors\0\u{3}display_indicator\0\u{3}disabled_zones_ratio\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._baseData) }()
      case 2: try { try decoder.decodeRepeatedInt32Field(value: &self.zonesColors) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.displayIndicator) }()
      case 4: try { try decoder.decodeRepeatedInt32Field(value: &self.disabledZonesRatio) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._baseData {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.zonesColors.isEmpty {
      try visitor.visitPackedInt32Field(value: self.zonesColors, fieldNumber: 2)
    }
    if self.displayIndicator != false {
      try visitor.visitSingularBoolField(value: self.displayIndicator, fieldNumber: 3)
    }
    if !self.disabledZonesRatio.isEmpty {
      try visitor.visitPackedInt32Field(value: self.disabledZonesRatio, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_BarData, rhs: Alkpb_BarData) -> Bool {
    if lhs._baseData != rhs._baseData {return false}
    if lhs.zonesColors != rhs.zonesColors {return false}
    if lhs.displayIndicator != rhs.displayIndicator {return false}
    if lhs.disabledZonesRatio != rhs.disabledZonesRatio {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_CompletionData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CompletionData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}base_data\0\u{3}done_color\0\u{3}to_do_color\0\u{3}completion_mode\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._baseData) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.doneColor) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.toDoColor) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.completionMode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._baseData {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.doneColor != 0 {
      try visitor.visitSingularInt32Field(value: self.doneColor, fieldNumber: 2)
    }
    if self.toDoColor != 0 {
      try visitor.visitSingularInt32Field(value: self.toDoColor, fieldNumber: 3)
    }
    if self.completionMode != .done {
      try visitor.visitSingularEnumField(value: self.completionMode, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_CompletionData, rhs: Alkpb_CompletionData) -> Bool {
    if lhs._baseData != rhs._baseData {return false}
    if lhs.doneColor != rhs.doneColor {return false}
    if lhs.toDoColor != rhs.toDoColor {return false}
    if lhs.completionMode != rhs.completionMode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_TextData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TextData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}icon_id\0\u{3}text_text\0\u{3}text_color\0\u{3}text_font_id\0\u{3}title_text\0\u{3}title_color\0\u{3}title_font_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.iconID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.textText) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.textColor) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.textFontID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.titleText) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.titleColor) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.titleFontID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.iconID != 0 {
      try visitor.visitSingularInt32Field(value: self.iconID, fieldNumber: 1)
    }
    if !self.textText.isEmpty {
      try visitor.visitSingularStringField(value: self.textText, fieldNumber: 2)
    }
    if self.textColor != 0 {
      try visitor.visitSingularInt32Field(value: self.textColor, fieldNumber: 3)
    }
    if self.textFontID != 0 {
      try visitor.visitSingularInt32Field(value: self.textFontID, fieldNumber: 4)
    }
    if !self.titleText.isEmpty {
      try visitor.visitSingularStringField(value: self.titleText, fieldNumber: 5)
    }
    if self.titleColor != 0 {
      try visitor.visitSingularInt32Field(value: self.titleColor, fieldNumber: 6)
    }
    if self.titleFontID != 0 {
      try visitor.visitSingularInt32Field(value: self.titleFontID, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_TextData, rhs: Alkpb_TextData) -> Bool {
    if lhs.iconID != rhs.iconID {return false}
    if lhs.textText != rhs.textText {return false}
    if lhs.textColor != rhs.textColor {return false}
    if lhs.textFontID != rhs.textFontID {return false}
    if lhs.titleText != rhs.titleText {return false}
    if lhs.titleColor != rhs.titleColor {return false}
    if lhs.titleFontID != rhs.titleFontID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_PlainTextData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PlainTextData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}text_text\0\u{3}text_color\0\u{3}text_font_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.textText) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.textColor) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.textFontID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.textText.isEmpty {
      try visitor.visitSingularStringField(value: self.textText, fieldNumber: 1)
    }
    if self.textColor != 0 {
      try visitor.visitSingularInt32Field(value: self.textColor, fieldNumber: 2)
    }
    if self.textFontID != 0 {
      try visitor.visitSingularInt32Field(value: self.textFontID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_PlainTextData, rhs: Alkpb_PlainTextData) -> Bool {
    if lhs.textText != rhs.textText {return false}
    if lhs.textColor != rhs.textColor {return false}
    if lhs.textFontID != rhs.textFontID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_ImageData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ImageData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}image_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.imageID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.imageID != 0 {
      try visitor.visitSingularInt32Field(value: self.imageID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_ImageData, rhs: Alkpb_ImageData) -> Bool {
    if lhs.imageID != rhs.imageID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_AnimData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AnimData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}anim_id\0\u{3}repeat_count\0\u{3}frame_time_ms\0\u{3}clean_at_end\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.animID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.repeatCount) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.frameTimeMs) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.cleanAtEnd) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.animID != 0 {
      try visitor.visitSingularInt32Field(value: self.animID, fieldNumber: 1)
    }
    if self.repeatCount != 0 {
      try visitor.visitSingularInt32Field(value: self.repeatCount, fieldNumber: 2)
    }
    if self.frameTimeMs != 0 {
      try visitor.visitSingularInt32Field(value: self.frameTimeMs, fieldNumber: 3)
    }
    if self.cleanAtEnd != false {
      try visitor.visitSingularBoolField(value: self.cleanAtEnd, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_AnimData, rhs: Alkpb_AnimData) -> Bool {
    if lhs.animID != rhs.animID {return false}
    if lhs.repeatCount != rhs.repeatCount {return false}
    if lhs.frameTimeMs != rhs.frameTimeMs {return false}
    if lhs.cleanAtEnd != rhs.cleanAtEnd {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_WidgetConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WidgetConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}metric\0\u{1}zones7\0\u{1}zones5\0\u{1}range\0\u{1}threshold\0\u{1}completion\0\u{1}text\0\u{3}short_text\0\u{3}plain_text\0\u{1}image\0\u{1}anim\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Alkpb_BaseData?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .metric(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .metric(v)
        }
      }()
      case 2: try {
        var v: Alkpb_BarData?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .zones7(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .zones7(v)
        }
      }()
      case 3: try {
        var v: Alkpb_BarData?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .zones5(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .zones5(v)
        }
      }()
      case 4: try {
        var v: Alkpb_BarData?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .range(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .range(v)
        }
      }()
      case 5: try {
        var v: Alkpb_BarData?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .threshold(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .threshold(v)
        }
      }()
      case 6: try {
        var v: Alkpb_CompletionData?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .completion(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .completion(v)
        }
      }()
      case 7: try {
        var v: Alkpb_TextData?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .text(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .text(v)
        }
      }()
      case 8: try {
        var v: Alkpb_TextData?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .shortText(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .shortText(v)
        }
      }()
      case 9: try {
        var v: Alkpb_PlainTextData?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .plainText(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .plainText(v)
        }
      }()
      case 10: try {
        var v: Alkpb_ImageData?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .image(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .image(v)
        }
      }()
      case 11: try {
        var v: Alkpb_AnimData?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .anim(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .anim(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.type {
    case .metric?: try {
      guard case .metric(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .zones7?: try {
      guard case .zones7(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .zones5?: try {
      guard case .zones5(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .range?: try {
      guard case .range(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .threshold?: try {
      guard case .threshold(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .completion?: try {
      guard case .completion(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .text?: try {
      guard case .text(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .shortText?: try {
      guard case .shortText(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .plainText?: try {
      guard case .plainText(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .image?: try {
      guard case .image(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .anim?: try {
      guard case .anim(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_WidgetConfig, rhs: Alkpb_WidgetConfig) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_RawPosition: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RawPosition"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}x\0\u{1}y\0\u{1}width\0\u{1}height\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.x) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.y) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.width) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.height) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x != 0 {
      try visitor.visitSingularInt32Field(value: self.x, fieldNumber: 1)
    }
    if self.y != 0 {
      try visitor.visitSingularInt32Field(value: self.y, fieldNumber: 2)
    }
    if self.width != 0 {
      try visitor.visitSingularInt32Field(value: self.width, fieldNumber: 3)
    }
    if self.height != 0 {
      try visitor.visitSingularInt32Field(value: self.height, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_RawPosition, rhs: Alkpb_RawPosition) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_Widget: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Widget"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}data_id\0\u{1}config\0\u{1}style\0\u{3}layout_position\0\u{3}raw_position\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.dataID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._config) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.style) }()
      case 4: try {
        var v: Alkpb_LayoutPosition?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.position != nil {try decoder.handleConflictingOneOf()}
          self.position = .layoutPosition(v)
        }
      }()
      case 5: try {
        var v: Alkpb_RawPosition?
        var hadOneofValue = false
        if let current = self.position {
          hadOneofValue = true
          if case .rawPosition(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.position = .rawPosition(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.dataID != 0 {
      try visitor.visitSingularInt32Field(value: self.dataID, fieldNumber: 1)
    }
    try { if let v = self._config {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.style != .half {
      try visitor.visitSingularEnumField(value: self.style, fieldNumber: 3)
    }
    switch self.position {
    case .layoutPosition?: try {
      guard case .layoutPosition(let v)? = self.position else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 4)
    }()
    case .rawPosition?: try {
      guard case .rawPosition(let v)? = self.position else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_Widget, rhs: Alkpb_Widget) -> Bool {
    if lhs.dataID != rhs.dataID {return false}
    if lhs._config != rhs._config {return false}
    if lhs.style != rhs.style {return false}
    if lhs.position != rhs.position {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_SetScreenRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetScreenRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}screen_id\0\u{1}widgets\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.screenID) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.widgets) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.screenID != 0 {
      try visitor.visitSingularInt32Field(value: self.screenID, fieldNumber: 1)
    }
    if !self.widgets.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.widgets, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_SetScreenRequest, rhs: Alkpb_SetScreenRequest) -> Bool {
    if lhs.screenID != rhs.screenID {return false}
    if lhs.widgets != rhs.widgets {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_DisplayScreenRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DisplayScreenRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}screen_id\0\u{3}transition_type\0\u{3}duration_ms\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.screenID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.transitionType) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.durationMs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.screenID != 0 {
      try visitor.visitSingularInt32Field(value: self.screenID, fieldNumber: 1)
    }
    if self.transitionType != .none {
      try visitor.visitSingularEnumField(value: self.transitionType, fieldNumber: 2)
    }
    if self.durationMs != 0 {
      try visitor.visitSingularInt32Field(value: self.durationMs, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_DisplayScreenRequest, rhs: Alkpb_DisplayScreenRequest) -> Bool {
    if lhs.screenID != rhs.screenID {return false}
    if lhs.transitionType != rhs.transitionType {return false}
    if lhs.durationMs != rhs.durationMs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_Value: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Value"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}left_value\0\u{3}middle_value\0\u{3}right_value\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.leftValue) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.middleValue) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.rightValue) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.leftValue.isEmpty {
      try visitor.visitSingularStringField(value: self.leftValue, fieldNumber: 1)
    }
    if !self.middleValue.isEmpty {
      try visitor.visitSingularStringField(value: self.middleValue, fieldNumber: 2)
    }
    if !self.rightValue.isEmpty {
      try visitor.visitSingularStringField(value: self.rightValue, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_Value, rhs: Alkpb_Value) -> Bool {
    if lhs.leftValue != rhs.leftValue {return false}
    if lhs.middleValue != rhs.middleValue {return false}
    if lhs.rightValue != rhs.rightValue {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_WidgetZoneData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WidgetZoneData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}chosen_zone\0\u{3}indicator_position\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.chosenZone) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.indicatorPosition) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.chosenZone != 0 {
      try visitor.visitSingularInt32Field(value: self.chosenZone, fieldNumber: 1)
    }
    if self.indicatorPosition != 0 {
      try visitor.visitSingularInt32Field(value: self.indicatorPosition, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_WidgetZoneData, rhs: Alkpb_WidgetZoneData) -> Bool {
    if lhs.chosenZone != rhs.chosenZone {return false}
    if lhs.indicatorPosition != rhs.indicatorPosition {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_WidgetData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WidgetData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}data_id\0\u{1}value\0\u{3}widget_zone_data\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.dataID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._value) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._widgetZoneData) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.dataID != 0 {
      try visitor.visitSingularInt32Field(value: self.dataID, fieldNumber: 1)
    }
    try { if let v = self._value {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._widgetZoneData {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_WidgetData, rhs: Alkpb_WidgetData) -> Bool {
    if lhs.dataID != rhs.dataID {return false}
    if lhs._value != rhs._value {return false}
    if lhs._widgetZoneData != rhs._widgetZoneData {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_UpdateWidgetsDataRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UpdateWidgetsDataRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}update_widgets\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.updateWidgets) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.updateWidgets.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.updateWidgets, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_UpdateWidgetsDataRequest, rhs: Alkpb_UpdateWidgetsDataRequest) -> Bool {
    if lhs.updateWidgets != rhs.updateWidgets {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_StopAnimRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StopAnimRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}data_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.dataID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.dataID != 0 {
      try visitor.visitSingularInt32Field(value: self.dataID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_StopAnimRequest, rhs: Alkpb_StopAnimRequest) -> Bool {
    if lhs.dataID != rhs.dataID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Alkpb_CommandWrapper: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CommandWrapper"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}set_screen\0\u{3}display_screen\0\u{3}update_widgets_data\0\u{3}stop_anim\0\u{3}save_asset\0\u{3}delete_asset\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Alkpb_SetScreenRequest?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .setScreen(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .setScreen(v)
        }
      }()
      case 2: try {
        var v: Alkpb_DisplayScreenRequest?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .displayScreen(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .displayScreen(v)
        }
      }()
      case 3: try {
        var v: Alkpb_UpdateWidgetsDataRequest?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .updateWidgetsData(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .updateWidgetsData(v)
        }
      }()
      case 4: try {
        var v: Alkpb_StopAnimRequest?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .stopAnim(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .stopAnim(v)
        }
      }()
      case 5: try {
        var v: Alkpb_SaveAssetRequest?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .saveAsset(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .saveAsset(v)
        }
      }()
      case 6: try {
        var v: Alkpb_DeleteAssetRequest?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .deleteAsset(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .deleteAsset(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.msg {
    case .setScreen?: try {
      guard case .setScreen(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .displayScreen?: try {
      guard case .displayScreen(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .updateWidgetsData?: try {
      guard case .updateWidgetsData(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .stopAnim?: try {
      guard case .stopAnim(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .saveAsset?: try {
      guard case .saveAsset(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .deleteAsset?: try {
      guard case .deleteAsset(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Alkpb_CommandWrapper, rhs: Alkpb_CommandWrapper) -> Bool {
    if lhs.msg != rhs.msg {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
